/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ControllerOrderLine model module.
 * @module model/ControllerOrderLine
 * @version v0
 */
export class ControllerOrderLine {
  /**
   * Constructs a new <code>ControllerOrderLine</code>.
   * @alias module:model/ControllerOrderLine
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ControllerOrderLine</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ControllerOrderLine} obj Optional instance to populate.
   * @return {module:model/ControllerOrderLine} The populated <code>ControllerOrderLine</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ControllerOrderLine();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
ControllerOrderLine.prototype.code = undefined;

/**
 * @member {String} description
 */
ControllerOrderLine.prototype.description = undefined;

/**
 * @member {Number} quantity
 */
ControllerOrderLine.prototype.quantity = undefined;

/**
 * @member {Number} price
 */
ControllerOrderLine.prototype.price = undefined;

