/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TransactionExecutionRequest model module.
 * @module model/TransactionExecutionRequest
 * @version v0
 */
export class TransactionExecutionRequest {
  /**
   * Constructs a new <code>TransactionExecutionRequest</code>.
   * @alias module:model/TransactionExecutionRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionExecutionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionExecutionRequest} obj Optional instance to populate.
   * @return {module:model/TransactionExecutionRequest} The populated <code>TransactionExecutionRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionExecutionRequest();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
TransactionExecutionRequest.prototype.amount = undefined;

