/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Transaction model module.
 * @module model/Transaction
 * @version v0
 */
export class Transaction {
  /**
   * Constructs a new <code>Transaction</code>.
   * @alias module:model/Transaction
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Transaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transaction} obj Optional instance to populate.
   * @return {module:model/Transaction} The populated <code>Transaction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Transaction();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('settledAmount'))
        obj.settledAmount = ApiClient.convertToType(data['settledAmount'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Transaction.prototype.id = undefined;

/**
 * @member {Date} _date
 */
Transaction.prototype._date = undefined;

/**
 * @member {Number} amount
 */
Transaction.prototype.amount = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Transaction.TypeEnum = {
  /**
   * value: "RESERVE"
   * @const
   */
  RESERVE: "RESERVE",

  /**
   * value: "CAPTURE"
   * @const
   */
  CAPTURE: "CAPTURE",

  /**
   * value: "REFUND"
   * @const
   */
  REFUND: "REFUND",

  /**
   * value: "RELEASE"
   * @const
   */
  RELEASE: "RELEASE"
};
/**
 * @member {module:model/Transaction.TypeEnum} type
 */
Transaction.prototype.type = undefined;

/**
 * @member {Number} settledAmount
 */
Transaction.prototype.settledAmount = undefined;

