/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Transaction} from './Transaction';

/**
 * The TransactionExecutionResponse model module.
 * @module model/TransactionExecutionResponse
 * @version v0
 */
export class TransactionExecutionResponse {
  /**
   * Constructs a new <code>TransactionExecutionResponse</code>.
   * @alias module:model/TransactionExecutionResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionExecutionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionExecutionResponse} obj Optional instance to populate.
   * @return {module:model/TransactionExecutionResponse} The populated <code>TransactionExecutionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionExecutionResponse();
      if (data.hasOwnProperty('transaction'))
        obj.transaction = Transaction.constructFromObject(data['transaction']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Transaction} transaction
 */
TransactionExecutionResponse.prototype.transaction = undefined;

