/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ShopOrder', function() {
      beforeEach(function() {
        instance = new OpenApiDefinition.ShopOrder();
      });

      it('should create an instance of ShopOrder', function() {
        // TODO: update the code to test ShopOrder
        expect(instance).to.be.a(OpenApiDefinition.ShopOrder);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property orderLines (base name: "orderLines")', function() {
        // TODO: update the code to test the property orderLines
        expect(instance).to.have.property('orderLines');
        // expect(instance.orderLines).to.be(expectedValueLiteral);
      });

      it('should have the property transactions (base name: "transactions")', function() {
        // TODO: update the code to test the property transactions
        expect(instance).to.have.property('transactions');
        // expect(instance.transactions).to.be(expectedValueLiteral);
      });

      it('should have the property orderAmount (base name: "orderAmount")', function() {
        // TODO: update the code to test the property orderAmount
        expect(instance).to.have.property('orderAmount');
        // expect(instance.orderAmount).to.be(expectedValueLiteral);
      });

      it('should have the property settledAmount (base name: "settledAmount")', function() {
        // TODO: update the code to test the property settledAmount
        expect(instance).to.have.property('settledAmount');
        // expect(instance.settledAmount).to.be(expectedValueLiteral);
      });

    });
  });

}));
