/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.29
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.ShopOrderControllerApi();
  });

  describe('(package)', function() {
    describe('ShopOrderControllerApi', function() {
      describe('capture', function() {
        it('should call capture successfully', function(done) {
          // TODO: uncomment, update parameter values for capture call and complete the assertions
          /*

          instance.capture(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApiDefinition.TransactionExecutionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createShopOrder', function() {
        it('should call createShopOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for createShopOrder call and complete the assertions
          /*

          instance.createShopOrder(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApiDefinition.ShopOrder);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('refund', function() {
        it('should call refund successfully', function(done) {
          // TODO: uncomment, update parameter values for refund call and complete the assertions
          /*

          instance.refund(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApiDefinition.TransactionExecutionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('release', function() {
        it('should call release successfully', function(done) {
          // TODO: uncomment, update parameter values for release call and complete the assertions
          /*

          instance.release(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApiDefinition.TransactionExecutionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('reserve', function() {
        it('should call reserve successfully', function(done) {
          // TODO: uncomment, update parameter values for reserve call and complete the assertions
          /*

          instance.reserve(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApiDefinition.TransactionExecutionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('shopOrder', function() {
        it('should call shopOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for shopOrder call and complete the assertions
          /*

          instance.shopOrder(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenApiDefinition.ShopOrder);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('shopOrders', function() {
        it('should call shopOrders successfully', function(done) {
          // TODO: uncomment shopOrders call and complete the assertions
          /*

          instance.shopOrders(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(OpenApiDefinition.ShopOrder);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
